[features]
seeds = false
skip-lint = false
[programs.localnet]
rps = "rpsVN2ZC1K9hoGPs83xahjWo46cDNP49Tk7rQb56ipE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
